"""Task-generation equivalence: do the ported triggers fire the tasks Unity fires?

Two separate claims, checked separately because they fail for different reasons:

  DRAW COUNT   a generation pass must consume exactly as many ProbabilityTrigger draws as
               Unity's, or every later draw in the round reads someone else's randoms. This
               is the one that must be exact -- it is stream position, not behaviour.
  FIRED SET    which tasks actually activate, compared against the tasks that APPEAR in the
               capture's next active list.

The draw count is checkable from the marks alone and is exact. The fired set depends on
context the game_state export only partly carries (per-facility resource storage, building
status), so it is reported as an agreement RATE with the missing inputs named, rather than
asserted as exact and quietly passing on a coincidence.
"""
import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from cora_sim.generation import (TriggerContext, generation_pass,  # noqa: E402
                                 suitable_facilities)
from cora_sim.rng import UnityRandom                              # noqa: E402
from cora_sim.triggers import INVENTORY                           # noqa: E402

_DEFAULT = ("/private/tmp/claude-501/-Users-cpulling-Work-CORA/"
            "b762a1aa-9f0c-4053-9897-bfd6aeeb9623/scratchpad/econ5_*.json")


def context_from(state):
    sb = state.get("satisfactionAndBudget") or {}
    wf = state.get("workforceState") or {}
    session = state.get("sessionInfo") or {}
    facilities = []
    for f in ((state.get("mapState") or {}).get("facilities") or []):
        res = dict(f.get("resources") or {})
        facilities.append({"type": f.get("buildingType"),
                           "name": f.get("facilityName"),
                           "prebuilt": f.get("facilityType") == "Prebuilt",
                           "operational": bool(f.get("isOperational")),
                           "status": f.get("buildingStatus"),
                           "resources": res})
    free = (wf.get("freeTrainedWorkers", 0) or 0) + (wf.get("freeUntrainedWorkers", 0) or 0)
    total = max(1, wf.get("totalAvailableWorkforce", 0) or 1)
    return TriggerContext(
        day=session.get("currentDay", 1), segment=session.get("currentRound", 1),
        # game_state reports the DISPLAY name ("Clear"), while the triggers switch on the
        # WeatherType enum ("Sunny"). The surrogate's World carries the enum name already,
        # so this map exists only to read captures.
        weather={"Clear": "Sunny"}.get(
            (state.get("environmentalConditions") or {}).get("weatherCondition", "Sunny"),
            (state.get("environmentalConditions") or {}).get("weatherCondition", "Sunny")),
        flood_tiles=((state.get("mapState") or {}).get("floodState") or {}).get("affectedRoads", 0),
        budget=sb.get("budget", 0), satisfaction=sb.get("satisfaction", 50.0),
        free_workforce=free, idle_ratio=100.0 * free / total, facilities=facilities)


def main(pattern=None):
    paths = sorted(glob.glob(pattern or os.environ.get("ECON_TRACES", _DEFAULT)))
    if not paths:
        print("  no traces found")
        print("\nRESULT: SKIPPED")
        return 0

    print("cora_sim.generation vs Unity")
    facilities_by_type = {}
    draw_rows, agree, total = [], 0, 0
    for path in paths:
        trace = json.load(open(path))
        prev = {}
        for step in trace:
            state = step["before"]
            ctx = context_from(state)
            ctx.prev = prev
            names = [f.get("facilityName") for f in
                     ((state.get("mapState") or {}).get("facilities") or [])
                     if f.get("buildingType") == "Community"]

            def facilities_for(task_def, _f=ctx.facilities):
                return suitable_facilities(task_def, _f)

            rng = UnityRandom(state=(1, 2, 3, 4))
            marks = []
            fired = generation_pass(rng, ctx, facilities_for, marks=marks)
            draw_rows.append(len(marks))
            before_ids = {t.get("stableTaskId") for t in (state.get("allActiveTasks") or [])}
            after_ids = {t.get("stableTaskId") for t in (step["after"].get("allActiveTasks") or [])}
            # Only DATABASE tasks are generated by triggers. Runtime-created ones --
            # casework requests from ClientStayTracker, the daily report -- come from
            # TaskSystem.CreateTask directly and carry an EMPTY stableTaskId, so counting
            # them here would score the trigger port against tasks it never claimed to
            # produce. They are the majority of what appears.
            appeared = {t for t in (after_ids - before_ids) if t}
            predicted = {tid for tid, _f in fired}
            if appeared:
                total += 1
                if predicted & appeared:
                    agree += 1
                elif agree < 3:               # show a few misses, to make a low rate legible
                    print(f"      round {step['round']}: unity started {sorted(appeared)}, "
                          f"port predicted {sorted(predicted) or 'nothing'}")

    # Unity's own count, read from the capture logs: 3 per pass throughout, because no
    # shelter ever became operational and prebuilt communities are the only suitable
    # facilities for the one task carrying a ProbabilityTrigger.
    expected = 3
    exact = all(d == expected for d in draw_rows)
    print(f"  probability draws/pass  : {sorted(set(draw_rows))} "
          f"(Unity: {expected} per pass, measured from its own logs)"
          f"{'' if exact else '  <-- STREAM WOULD DESYNC'}")
    if total:
        print(f"  fired-set overlap       : {agree}/{total} rounds (INDICATIVE ONLY)")
    print("  WHY INDICATIVE          : the fired set cannot be checked from a capture, "
          "because game_state does not carry the inputs the conditions read:")
    print("      * the SEGMENT a generation pass runs at (passes fire at segments 0/1/2; "
          "sessionInfo.currentRound is the round, not the pass)")
    print("      * the flood TILE COUNT (only affectedRoads and waterLevel are exported)")
    print("      * the exact workforce ratio WorkforceTrigger compares against")
    print("    The surrogate's World carries all three directly, so generation is exercised "
          "properly by the closed-loop test rather than here. What IS checkable from a "
          "capture -- and is what the RNG stream depends on -- is the draw count.")
    print("\nRESULT:", "ALL PASS" if exact else "FAILURES PRESENT")
    return 0 if exact else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1 else None))
